spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost/cegedim_hackathon
    username: SAMPLE
    password: 12345
jwt:
  secret: ahmedeliwa