spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost/cegedim_hackathon
    username: SAMPLE
    password: 12345
jwt:
  secret: ahmedeliwa
#  spring.jpa.properties.hibernate.
#  spring.jpa.properties.hibernate.dialect.storage_engine=innodb